export const LOAD_HOLDER_SUCCESS = 'LOAD_HOLDER_SUCCESS';
export const ADD_HOLDER_SUCCESS = 'ADD_HOLDER_SUCCESS';
export const ENABLE_LOGIN_SUCCESS = 'ENABLE_LOGIN_SUCCESS';
export const DISABLE_LOGIN_SUCCESS = 'DISABLE_LOGIN_SUCCESS';
