export const ENABLE_LOGIN_SUCCESS = 'ENABLE_LOGIN_SUCCESS';
export const DISABLE_LOGIN_SUCCESS = 'DISABLE_LOGIN_SUCCESS';
export const ENABLE_USER_LOAD = 'ENABLE_USER_LOAD';
export const BUILD_NEW_GITHUB_DEMO_MODEL_SUCCESS = 'BUILD_NEW_GITHUB_DEMO_MODEL_SUCCESS';
