# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputcomponent',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outputcomponent',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
