# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_demo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='permalink',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
